// The primer's prose, verbatim from docs/plans/filter-primer.md. Owner copy:
// every string here ships character for character as approved, and the markup
// the owner wrote — `**strong**`, `*stressed*`, bullet lists — is kept in the
// string and turned into tags by the view (./View.js), so the source of truth
// stays a document the owner can read and diff against the plan.
//
// Shape: the intro's paragraphs, then one entry per section with its heading and
// its blocks. A block is a paragraph string or a list of item strings.

/** @typedef {string | string[]} Block */

/** @type {string[]} */
export const INTRO = [
  "Choosing a filter is easy: you just need a few simple concepts.",
  "If you're still overwhelmed after reading the below, try Easy Mode! It offers a truly jargon-free approach to choosing some of the best filters in the program.",
];

/** @type {{ id: string, heading: string, blocks: Block[] }[]} */
export const SECTIONS = [
  {
    id: "phase-length",
    heading: "Phase and Length",
    blocks: [
      "Filter design is a game of trade-offs: a filter can be accurate in time to give better transients, or it can be accurate in frequency to give a better sense of space. Rather than reaching for the extremes, most filters strike a balance while still emphasizing one over the other.",
      "This tension revolves around the concept of 'ringing', or how a filter spreads out a transient in time. It has two axes:",
      [
        "Where it occurs, i.e., whether any ringing occurs before the transient or only after",
        "How long it is, i.e., how smeared the transient is in time",
      ],
      "**Where ringing occurs** is determined by a filter's **phase**. Linear phase ensures that all frequencies arrive at the same time to improve the sense of space, but it pays for this with an unnatural side-effect: pre-ringing, or ringing that occurs *before* the transient actually happens, weakening transient reproduction. Minimum phase filters only ring after the transient, which sounds more natural, at the cost of higher frequencies arriving later than the rest, marring the sense of space.",
      "**How long the ringing is** is set by a filter's **length**. Longer filters are more capable of separating the music from the junk generated by the digital-to-analog conversion, giving a better sense of space from cleaner high-frequency performance at the cost of smearing transients more; shorter filters ring and therefore smear less, giving cleaner transients at the cost of more junk leaking through, distorting the higher frequencies and with them the sense of space.",
      "When you're asked to choose between longer and shorter, or linear and minimum phase, ask yourself: do I care more about cleaner transients, or the recording's natural sense of space? Multi-track studio recordings have an artificial sense of space at best, but often have strong transient content like percussion, and are therefore more suited to shorter and/or minimum phase filters; live or acoustic performances where the space is part of the recording benefit more from longer and/or linear phase filters.",
      "Lastly, you'll notice that HQPlayer offers far more linear phase filters than minimum. This is because pre-ringing is only really troublesome when a filter is long enough; many linear phase filters pre-ring so little that minimum phase variants would add nothing of value. Length is therefore the more important of the two properties: the manual's own genre guidance is organized by length, not phase.",
    ],
  },
  {
    id: "roll-off",
    heading: "Roll-off",
    blocks: [
      'The process of converting digital music back to analog generates ultrasonic junk tones called images. Without a filter, images can wreak havoc by folding down into the audible range during downstream analog stages as distortions. Filters generate a cliff that tries to keep music at the top and images at the bottom. A filter\'s "roll-off" character describes the shape of that cliff:',
      ["at what frequency the cliff begins", "how steep the cut is", "how far down it goes"],
      'The cliff effect, as with so many things, comes at a price: ringing. A filter\'s length determines how long it rings or smears the transient in time; it may also be thought of as a "budget" to be spent on the shape of the cliff. "Slow" or "gentle" filters roll off gradually, fading the top of the music while letting some junk through; "fast" or "steep" filters have a sharper cliff and are therefore better able to separate music from junk.',
      "The faster a filter is, however, the more it costs, and the longer it rings. A shorter filter that spends its budget well for the content at hand will therefore outperform a longer filter that spends where it isn't needed, all while producing cleaner transients and using fewer resources.",
      'When selecting a roll-off character, ask yourself: how much do I trust the top end of this recording? Technically clean, well-mastered content has little junk lurking near the top of the music, so a gentle cliff that starts as late as possible yields the best results; these are, for example, the "extended frequency response" variants, with half-band and Gaussian half-band being the extremes. Compressed, harsh, or otherwise suspect studio work can have more junk than music up top and are better served by fast and aggressive filters, even if it ends up taking some music with it. These are exemplified by the "extreme roll-off and attenuation" variants.',
      "When in doubt, go Gaussian: these represent the best-case solution to the time-frequency tension, ring minimally, and optimally balance music retention and junk removal.",
    ],
  },
];
