// Pipeline `process` chain parser/serializer (manual §7.1). A chain is a
// comma-separated stage list; each stage is either a plugin spec
// ("<plugin>:arg;arg=val;...", plugins iir/delay/riaa, case-sensitive) or a
// filter-impulse filename (convolution). Round-trip contract (matrix-spec §4):
// parse(s) then serialize is byte-identical — each stage keeps its original
// `raw` string, regenerated only when the stage is edited (buildRaw).

/**
 * @typedef {Record<string, string>} StageArgs
 *   One stage's arguments verbatim off the wire — every value is a decimal
 *   string, and a valueless argument ("subsonic") carries "".
 * @typedef {{ kind: string, args?: StageArgs, file?: string, raw?: string }} MatrixStage
 *   One pipeline stage. A plugin stage carries `args`; a convolution stage
 *   carries `file`. `raw` is the original chain text, kept byte-identical for
 *   the round-trip and regenerated by buildRaw only when the stage is edited.
 * @typedef {{ args: string[], oneOf?: string[] }} IirSchema
 *   One iir type's required arguments plus its one-of group.
 * @typedef {{ source: string, mixdown: string, gain: string, gainunit: string, process: string }} PipelineRow
 *   One matrix pipeline row as the wire carries it — every field a string,
 *   including the channel indexes. Lives here rather than in each consumer
 *   because the crossfeed compilers, the recognizers and the EQ importer/
 *   exporter all read and write the same five fields.
 */

// MatrixStage is a union in disguise: `args` belongs to the plugin stages and
// `file` to the convolution stage, so each is absent on the other's kind and the
// type cannot say which without a discriminator every consumer would have to
// narrow on. These read one side; the empty value a wrong-kind stage yields is
// what the absent key already meant — no args is no args, no file is no file.
/**
 * A plugin stage's arguments, empty on a convolution stage.
 * @param {MatrixStage} stage
 * @returns {StageArgs}
 */
export const stageArgs = (stage) => stage.args || {};
/**
 * A convolution stage's impulse filename, empty on a plugin stage.
 * @param {MatrixStage} stage
 * @returns {string}
 */
const stageFile = (stage) => stage.file || "";

const PLUGINS = new Set(["iir", "delay", "riaa"]);

/**
 * Split a chain into its stages, classifying each as a plugin spec or a
 * convolution filename and keeping its original text in `raw`.
 * @param {string} str the chain text
 * @returns {MatrixStage[]}
 */
export function parseProcess(str) {
  if (!str || !str.trim()) return [];
  return str.split(",").map((raw) => {
    const colon = raw.indexOf(":");
    // Head is trimmed for CLASSIFICATION only — `raw` stays byte-identical for
    // the round-trip. A bare plugin name with no colon ("riaa") is a legal
    // zero-arg spec, not a convolution filename.
    const head = (colon === -1 ? raw : raw.slice(0, colon)).trim();
    if (PLUGINS.has(head)) {
      /** @type {StageArgs} */
      const args = {};
      for (const part of (colon === -1 ? "" : raw.slice(colon + 1)).split(";")) {
        if (!part) continue;
        const eq = part.indexOf("=");
        if (eq === -1) args[part] = "";
        else args[part.slice(0, eq)] = part.slice(eq + 1);
      }
      return { kind: head, args, raw };
    }
    return { kind: "conv", file: raw, raw };
  });
}

/**
 * @param {MatrixStage} stage
 * @returns {string}
 */
function buildRaw(stage) {
  if (stage.kind === "conv") return stageFile(stage);
  const args = Object.entries(stageArgs(stage))
    .map(([k, v]) => (v === "" ? k : `${k}=${v}`))
    .join(";");
  return `${stage.kind}:${args}`;
}

/**
 * Join stages back into chain text, each stage emitting its untouched `raw` or,
 * if it was edited, a freshly built spec.
 * @param {MatrixStage[]} stages
 * @returns {string}
 */
export function serializeProcess(stages) {
  return stages.map((s) => (s.raw !== undefined ? s.raw : buildRaw(s))).join(",");
}

// Not called `fmt`: Knob has a local of that name meaning something else
// entirely (a value at a step's precision).
/**
 * A number as stage-argument text, rounded to `dp` places and carrying no
 * trailing zeros — the shape buildRaw emits, so a synthesized chain round-trips
 * byte-identically through parseProcess.
 */
export const fmtArg = (/** @type {number} */ x, /** @type {number} */ dp) =>
  String(Math.round(x * 10 ** dp) / 10 ** dp);

// Loading a headphone profile replaces the previous profile rather than stacking
// on it, but "the previous profile" means the iir stages — a delay, a RIAA curve
// or a convolution someone put in the same chain is not EQ and is not ours to drop.
/**
 * Everything in a chain that ISN'T parametric EQ, order preserved.
 * @param {string} process the chain text
 * @returns {string}
 */
export function withoutEq(process) {
  return serializeProcess(parseProcess(process).filter((s) => s.kind !== "iir"));
}

// --- stage editor support (matrix-spec.md "Stage editor") --------------------

// Per-plugin argument schema (manual §7.2–7.4, case-sensitive). IIR types list
// their required args plus a one-of group (q OR bw OR s per type); biquad is
// raw coefficients. Values are free decimal strings — the daemon parses them.
/** @type {Record<string, IirSchema>} */
export const IIR_TYPES = {
  lp: { args: ["f"], oneOf: ["q", "s"] },
  lp1: { args: ["f"] },
  hp: { args: ["f"], oneOf: ["q", "s"] },
  hp1: { args: ["f"] },
  bp: { args: ["f"], oneOf: ["q", "bw"] },
  ap: { args: ["f"], oneOf: ["q", "bw"] },
  notch: { args: ["f"], oneOf: ["q", "bw"] },
  peak: { args: ["f", "g"], oneOf: ["q", "bw"] },
  lshelf: { args: ["f", "g"], oneOf: ["q", "s"] },
  hshelf: { args: ["f", "g"], oneOf: ["q", "s"] },
  biquad: { args: ["b0", "b1", "b2", "a0", "a1", "a2"] },
};
export const DELAY_ARGS = ["s", "t", "d", "v"];

const NUM = /^-?\d+(\.\d+)?([eE]-?\d+)?$/;

// Per-kind validators. Private by design: the contract is validateStage's
// return value, and tests/js/matrixspec.test.js reaches all of these through it.
/**
 * @param {MatrixStage} stage
 * @returns {string[]}
 */
function convIssues(stage) {
  return stageFile(stage).trim() ? [] : ["convolution stage has no file"];
}

/**
 * @param {StageArgs} args
 * @returns {string[]}
 */
function riaaIssues(args) {
  return Object.entries(args).flatMap(([k, v]) => {
    if (k !== "subsonic") return [`unknown riaa argument "${k}"`];
    return v === "0" || v === "1" ? [] : ["subsonic must be 0 or 1"];
  });
}

/**
 * @param {StageArgs} args
 * @returns {string[]}
 */
function delayIssues(args) {
  const issues = Object.entries(args).flatMap(([k, v]) =>
    !DELAY_ARGS.includes(k) ? [`unknown delay argument "${k}"`] : NUM.test(v) ? [] : [`${k} must be a number`],
  );
  // v is a known argument but sets the speed of sound, not a delay quantity.
  if (!["s", "t", "d"].some((k) => k in args)) issues.push("delay needs s, t, or d");
  return issues;
}

// Arguments that don't belong to this iir type, and values that aren't numbers.
/**
 * @param {StageArgs} args
 * @param {string} type
 * @param {IirSchema} schema
 * @returns {string[]}
 */
function iirArgIssues(args, type, schema) {
  const known = new Set(["type", ...schema.args, ...(schema.oneOf || [])]);
  return Object.entries(args).flatMap(([k, v]) => {
    if (k === "type") return [];
    if (!known.has(k)) return [`"${k}" does not apply to ${type}`];
    return NUM.test(v) ? [] : [`${k} must be a number`];
  });
}

// The one-of group (q OR bw OR s), per type. Types without a group skip it.
/**
 * @param {StageArgs} args
 * @param {string} type
 * @param {string[] | undefined} oneOf
 * @returns {string[]}
 */
function iirOneOfIssues(args, type, oneOf) {
  if (!oneOf) return [];
  const present = oneOf.filter((k) => k in args);
  if (present.length === 0) return [`${type} needs ${oneOf.join(" or ")}`];
  if (present.length > 1) return [`use only one of ${oneOf.join("/")}`];
  return [];
}

/**
 * @param {StageArgs} args
 * @returns {string[]}
 */
function iirIssues(args) {
  const type = args.type;
  const schema = IIR_TYPES[type];
  if (!schema) return [type ? `unknown iir type "${type}"` : "iir stage has no type"];
  return [
    ...iirArgIssues(args, type, schema),
    ...schema.args.filter((req) => !(req in args)).map((req) => `${type} needs ${req}`),
    ...iirOneOfIssues(args, type, schema.oneOf),
  ];
}

// Any kind that isn't conv/riaa/delay validates as iir, as it always has.
/** @type {Record<string, (args: StageArgs) => string[]>} */
const KIND_ISSUES = { riaa: riaaIssues, delay: delayIssues, iir: iirIssues };

// A stage with issues still renders and still serializes — validation informs,
// it never drops or rewrites user input.
/**
 * Issues for one stage, as plain strings.
 * @param {MatrixStage} stage
 * @returns {string[]}
 */
export function validateStage(stage) {
  if (stage.kind === "conv") return convIssues(stage);
  return (KIND_ISSUES[stage.kind] || iirIssues)(stageArgs(stage));
}

/**
 * Fresh stage of a kind, with sensible defaults (add-stage lands editable).
 * @param {string} kind
 * @returns {MatrixStage}
 */
export function newStage(kind) {
  if (kind === "conv") return { kind, file: "", raw: undefined };
  if (kind === "delay") return { kind, args: { t: "0.01" }, raw: undefined };
  if (kind === "riaa") return { kind, args: { subsonic: "1" }, raw: undefined };
  return { kind: "iir", args: { type: "peak", f: "1000", q: "1", g: "0" }, raw: undefined };
}

/**
 * A stage rebuilt after an edit: raw regenerates from params in schema order
 * (type, f, q/bw/s, g / coefficients), case-sensitively.
 * @param {MatrixStage} stage
 * @param {Record<string, string>} patch changed arguments (or `file` on a conv stage)
 * @returns {MatrixStage}
 */
export function editedStage(stage, patch) {
  if (stage.kind === "conv") {
    const next = { ...stage, ...patch };
    return { ...next, raw: next.file };
  }
  const args = { ...stage.args, ...patch };
  for (const k of Object.keys(args)) {
    if (args[k] === "" || args[k] === undefined) delete args[k];
  }
  const order =
    stage.kind === "iir"
      ? ["type", "f", "q", "bw", "s", "g", "b0", "b1", "b2", "a0", "a1", "a2"]
      : stage.kind === "delay"
        ? DELAY_ARGS
        : ["subsonic"];
  /** @type {StageArgs} */
  const ordered = {};
  for (const k of order) {
    if (k in args) ordered[k] = args[k];
  }
  const next = { ...stage, args: ordered };
  return { ...next, raw: buildRaw(next) };
}

// Per-kind labellers, private for the same reason as the validators above.
// A path with no basename ("impulses/") falls back to the whole string.
/**
 * @param {string} file
 * @returns {string}
 */
function convLabel(file) {
  return file.split("/").pop() || file;
}

// Which quantities reach an IIR chip, in order. Frequency and gain are each
// shown only when set, so their presence is behavior; the units and separators
// around them are not.
/**
 * @param {StageArgs} args
 * @returns {[string, string][]} each as [unit, value]
 */
function iirQuantities(args) {
  /** @type {[string, string][]} */
  const q = [];
  if (args.f) q.push(["Hz", String(args.f)]);
  if (args.g) q.push(["dB", String(args.g)]);
  return q;
}

/**
 * @param {StageArgs} args
 * @returns {string}
 */
function iirLabel(args) {
  const bits = [args.type || "iir", ...iirQuantities(args).map(([unit, v]) => `${v} ${unit}`)];
  return bits.join(" · ");
}

// t wins over s wins over d; v alone carries no quantity and leaves it bare.
// The precedence is the behavior here, so it is decided once, in the units, and
// the sentence is assembled from the result.
/**
 * @param {StageArgs} args
 * @returns {[string, string][]} the winning quantity as [unit, value], or empty
 */
function delayQuantities(args) {
  if (args.t) return [["s", String(args.t)]];
  if (args.s) return [["smp", String(args.s)]];
  if (args.d) return [["m", String(args.d)]];
  return [];
}

/**
 * @param {StageArgs} args
 * @returns {string}
 */
function delayLabel(args) {
  const [q] = delayQuantities(args);
  return q ? `delay · ${q[1]} ${q[0]}` : "delay";
}

/** @type {Record<string, (args: StageArgs) => string>} */
const KIND_LABEL = { iir: iirLabel, delay: delayLabel };

// What the chip label is made of, before it is made. `name` is what the stage is
// called — the IIR type, the convolution's basename, else the kind itself — and
// `quantities` are the figures that reach the chip, each with its unit. The
// separators and the order they are joined in are the label's business.
/**
 * @typedef {{ kind: string, name: string, quantities: [string, string][] }} StageParts
 */

/**
 * The parts a stage's chip label is built from, without building it.
 * @param {MatrixStage} stage
 * @returns {StageParts}
 */
export function stageParts(stage) {
  if (stage.kind === "conv") return { kind: "conv", name: convLabel(stageFile(stage)), quantities: [] };
  const args = stageArgs(stage);
  if (stage.kind === "iir") return { kind: "iir", name: String(args.type || "iir"), quantities: iirQuantities(args) };
  if (stage.kind === "delay") return { kind: "delay", name: "delay", quantities: delayQuantities(args) };
  return { kind: stage.kind, name: stage.kind, quantities: [] }; // riaa
}

/**
 * Chip label: the shortest string that identifies the stage at a glance.
 * @param {MatrixStage} stage
 * @returns {string}
 */
export function stageLabel(stage) {
  if (stage.kind === "conv") return convLabel(stageFile(stage));
  const label = KIND_LABEL[stage.kind];
  return label ? label(stageArgs(stage)) : stage.kind; // riaa
}
